services:
  db:
    image: postgres:15-alpine
    container_name: event_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=event_db
      - POSTGRES_USER=sofokl
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: event_web_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - "./.env"
    depends_on:
      - db

volumes:
  postgres_data:
